version: '3.7'
networks:
  onedayradio:
    external:
      name: onedayradio
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    expose:
      - '27017'
    command: mongod
    networks:
      - onedayradio
    environment:
      - MONGO_INITDB_ROOT_USERNAME=onedayradio-admin
      - MONGO_INITDB_ROOT_PASSWORD=password
