version: '3.7'
networks:
  onedayradio:
    external:
      name: onedayradio
services:
  neo4j-seed:
    build:
      context: ./localdb
      dockerfile: Dockerfile
    container_name: neo4j-seed
    command: ['./wait-for-it.sh', 'neo4j:7474', '--', './neo4j-seed.sh']
    depends_on:
      - neo4j
    networks:
      - onedayradio
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    networks:
      - onedayradio
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data \
      - $HOME/neo4j/logs:/logs \
      - $HOME/neo4j/import:/var/lib/neo4j/import \
      - $HOME/neo4j/plugins:/plugins \
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
