service: one-day-radio-api
app: one-day-radio-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  timeout: 30
  environment:
    mongodb_url: ${ssm:/onedayradio/${self:custom.myStage}/mongodb_url}
    frontend_url: ${ssm:/onedayradio/${self:custom.myStage}/frontend_url}
    spotify_redirect_url: ${ssm:/onedayradio/${self:custom.myStage}/spotify_redirect_url}
    spotify_client_id: ${ssm:/onedayradio/${self:custom.myStage}/spotify_client_id}
    spotify_client_secret: ${ssm:/onedayradio/${self:custom.myStage}/spotify_client_secret~true}
    spotify_scopes: ${ssm:/onedayradio/${self:custom.myStage}/spotify_scopes}
    token_secret: ${ssm:/onedayradio/${self:custom.myStage}/token_secret~true}
    token_expiration: ${ssm:/onedayradio/${self:custom.myStage}/token_expiration}
    security_salt_rounds: ${ssm:/onedayradio/${self:custom.myStage}/security_salt_rounds}

custom:
  myStage: ${opt:stage, self:provider.stage}
  serverless-offline:
    useChildProcesses: true
  serverless-offline-ssm:
    stages:
      - dev

functions:
  graphql:
    handler: src/handler.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  spotifyAuth:
    handler: src/spotify.handlers.authorize
    events:
      - http:
          path: spotify/auth
          method: get
          cors: true
  spotifyAuthCallback:
    handler: src/spotify.handlers.authCallback
    events:
      - http:
          path: spotify/auth/callback
          method: get
          cors: true

plugins:
  - serverless-offline-ssm
  - serverless-plugin-typescript
  - serverless-offline
