import { ids } from '../fixtures-ids'

module.exports = [
  {
    _id: ids.playlistSongs.metalWrathchildId,
    user: ids.users.juanId,
    playlist: ids.playlist.metalId,
    spotifyId: '1SpuDZ7y1W4vaCzHeLvsf7',
    spotifyUri: 'spotify:track:1SpuDZ7y1W4vaCzHeLvsf7',
    name: 'Wrathchild - 2015 Remaster',
    artists: 'Iron Maiden',
    createdAt: '2018-04-26T18:11:16.367Z',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.metalTheTrooperId,
    user: ids.users.pabloId,
    playlist: ids.playlist.metalId,
    spotifyId: '4OROzZUy6gOWN4UGQVaZMF',
    spotifyUri: 'spotify:track:4OROzZUy6gOWN4UGQVaZMF',
    name: 'The Trooper - 2015 Remaster',
    artists: 'Iron Maiden',
    createdAt: '2020-04-26T18:11:16.367Z',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.metalRawDealId,
    user: ids.users.juanId,
    playlist: ids.playlist.metalId,
    spotifyId: '2QagWuAL61R8DLydEte3tw',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte3tw',
    name: 'Raw Deal',
    artists: 'Judas Priest',
    createdAt: '2019-04-26T18:11:16.367Z',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.rockBleedItOut,
    user: ids.users.sanId,
    playlist: ids.playlist.rockId,
    spotifyId: '2QagWuAL61R8DLydEte3t1',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte3t1',
    name: 'Bleed it out',
    artists: 'Linkin Park',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.rockFaint,
    user: ids.users.sanId,
    playlist: ids.playlist.rockId,
    spotifyId: '2QagWuAL61R8DLydEte3t2',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte3t2',
    name: 'Faint',
    artists: 'Linkin Park',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.rockOneMoreLight,
    user: ids.users.sanId,
    playlist: ids.playlist.rockId,
    spotifyId: '2QagWuAL61R8DLydEte3t3',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte3t3',
    name: 'One More Light',
    artists: 'Linkin Park',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.rockPushingMeAway,
    user: ids.users.sanId,
    playlist: ids.playlist.rockId,
    spotifyId: '2QagWuAL61R8DLydEte3t4',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte3t4',
    name: 'Pushing Me Away',
    artists: 'Linkin Park',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.rockSomewhereIBelong,
    user: ids.users.sanId,
    playlist: ids.playlist.rockId,
    spotifyId: '2QagWuAL61R8DLydEte3t5',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte3t5',
    name: 'Somewhere I Belong',
    artists: 'Linkin Park',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.rockTheMessenger,
    user: ids.users.sanId,
    playlist: ids.playlist.rockId,
    spotifyId: '2QagWuAL61R8DLydEte3t6',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte3t6',
    name: 'The Messenger',
    artists: 'Linkin Park',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.popBillieJean,
    user: ids.users.juanId,
    playlist: ids.playlist.popId,
    spotifyId: '2QagWuAL61R8DLydEte311',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte311',
    name: 'Billie Jean',
    artists: 'Michael Jackson',
    createdAt: '2020-04-26T18:11:16.367Z',
    removedFromSpotify: false,
  },
  {
    _id: ids.playlistSongs.popSmoothCriminal,
    user: ids.users.sanId,
    playlist: ids.playlist.popId,
    spotifyId: '2QagWuAL61R8DLydEte333',
    spotifyUri: 'spotify:track:2QagWuAL61R8DLydEte333',
    name: 'Smooth Criminal',
    artists: 'Michael Jackson',
    createdAt: '2018-04-26T18:11:16.367Z',
    removedFromSpotify: false,
  },
]
